[package]
name = "piped-opengraph"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = "1.0"
serde_json = "1"
reqwest = "0.11"
html-escape = "0.2"
piped-rust-sdk = { git = "https://github.com/TeamPiped/piped-rust-sdk.git", package = "piped" }
